import { Terminal, Briefcase, FlaskConical, Palette, Languages, Theater, Megaphone, Heart, User, Calculator, Music, Camera } from 'lucide-react';
import { Category, Course } from './types';

export const CATEGORIES: Category[] = [
  { id: 'tech', name: 'Tech', icon: Terminal, description: 'Coding, AI, Cybersecurity, and Cloud Computing.' },
  { id: 'business', name: 'Business', icon: Briefcase, description: 'Entrepreneurship, Finance, and Management.' },
  { id: 'science', name: 'Science', icon: FlaskConical, description: 'Physics, Biology, Chemistry, and Astronomy.' },
  { id: 'design', name: 'Design', icon: Palette, description: 'UI/UX, Graphic Design, and Motion Graphics.' },
  { id: 'languages', name: 'Languages', icon: Languages, description: 'Spanish, French, Mandarin, and more.' },
  { id: 'arts', name: 'Arts', icon: Theater, description: 'History, Literature, and Philosophy.' },
  { id: 'marketing', name: 'Marketing', icon: Megaphone, description: 'Digital Marketing, SEO, and Brand Strategy.' },
  { id: 'health', name: 'Health', icon: Heart, description: 'Nutrition, Fitness, and Mental Wellness.' },
  { id: 'personal-dev', name: 'Personal Dev', icon: User, description: 'Productivity, Leadership, and Soft Skills.' },
  { id: 'math', name: 'Math', icon: Calculator, description: 'Calculus, Statistics, and Discrete Math.' },
  { id: 'music', name: 'Music', icon: Music, description: 'Theory, Production, and Instrument Mastery.' },
  { id: 'photography', name: 'Photography', icon: Camera, description: 'Composition, Lighting, and Post-Processing.' },
];

export const POPULAR_COURSES: Course[] = [
  {
    id: '1',
    title: 'Neural Networks 101',
    provider: 'Coursera',
    duration: '24h total',
    level: 'Intermediate',
    description: 'Master the fundamentals of deep learning and backpropagation from industry experts.',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800',
    categoryId: 'tech',
    url: 'https://www.coursera.org/learn/neural-networks-deep-learning',
  },
  {
    id: '2',
    title: 'UX Design Principles',
    provider: 'edX',
    duration: '12h total',
    level: 'Beginner',
    description: 'Learn how to create user-centric experiences through research and rapid prototyping.',
    image: 'https://images.unsplash.com/photo-1586717791821-3f44a563eb4c?auto=format&fit=crop&q=80&w=800',
    categoryId: 'design',
    url: 'https://www.edx.org/learn/user-experience-design',
  },
  {
    id: '3',
    title: 'Microeconomics Masterclass',
    provider: 'Khan Academy',
    duration: '40h total',
    level: 'Advanced',
    description: 'A deep dive into supply, demand, and market equilibrium for serious students.',
    image: 'https://images.unsplash.com/photo-1611974717537-484418a4122a?auto=format&fit=crop&q=80&w=800',
    categoryId: 'business',
    url: 'https://www.khanacademy.org/economics-finance-domain/microeconomics',
  },
  {
    id: '4',
    title: 'Creative Writing 101',
    provider: 'FutureLearn',
    duration: '8h total',
    level: 'Beginner',
    description: 'Unlock your storytelling potential through guided exercises and peer feedback.',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800',
    categoryId: 'arts',
    url: 'https://www.futurelearn.com/courses/creative-writing',
  },
  {
    id: '5',
    title: 'Python for Data Science',
    provider: 'Coursera',
    duration: '30h total',
    level: 'Beginner',
    description: 'Start your journey into data analysis with Python, NumPy, and Pandas.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800',
    categoryId: 'tech',
    url: 'https://www.coursera.org/learn/python-for-applied-data-science',
  },
  {
    id: '6',
    title: 'Digital Marketing Strategy',
    provider: 'Google',
    duration: '15h total',
    level: 'Beginner',
    description: 'Learn the core pillars of digital marketing: SEO, SEM, and Social Media.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    categoryId: 'marketing',
    url: 'https://grow.google/certificates/digital-marketing-ecommerce/',
  },
  {
    id: '7',
    title: 'Introduction to Astronomy',
    provider: 'edX',
    duration: '20h total',
    level: 'Beginner',
    description: 'Explore the wonders of the universe, from planets to distant galaxies.',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80&w=800',
    categoryId: 'science',
    url: 'https://www.edx.org/learn/astronomy',
  },
  {
    id: '8',
    title: 'Financial Markets',
    provider: 'Yale University',
    duration: '35h total',
    level: 'Intermediate',
    description: 'An overview of the ideas, methods, and institutions that permit human society to manage risks.',
    image: 'https://images.unsplash.com/photo-1611974717537-484418a4122a?auto=format&fit=crop&q=80&w=800',
    categoryId: 'business',
    url: 'https://www.coursera.org/learn/financial-markets-global',
  },
  {
    id: '9',
    title: 'Cloud Computing Fundamentals',
    provider: 'AWS',
    duration: '10h total',
    level: 'Beginner',
    description: 'Learn the basics of cloud computing, storage, and networking on AWS.',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
    categoryId: 'tech',
    url: 'https://aws.amazon.com/training/digital/cloud-practitioner-essentials/',
  },
  {
    id: '10',
    title: 'Cybersecurity for Everyone',
    provider: 'IBM',
    duration: '18h total',
    level: 'Beginner',
    description: 'Protect yourself and your organization from cyber threats with this comprehensive guide.',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800',
    categoryId: 'tech',
    url: 'https://www.coursera.org/specializations/cybersecurity',
  },
  {
    id:'11',
    title: 'Computer architecture',
    provider: 'IBM',
    duration: '20h total',
    level: 'Beginner',
    description: 'indepth understanding of computer systems',
    image: 'https://images.unsplash.com/photo-1760539165425-f76a6da1e50e?q=80&w=928&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    categoryId: 'tech',
    url: ''

  }
];